### ISSUE TITLE
Detail view component doesn't listen to changes in url

### ISSUE THREAD

**Issue by AoNoOokami** [rero/ng-core#142]
**Describe the issue**
When the url is changed from a detail component, the content is not updated excepted if we reload the application.

**To Reproduce**
In rero-ils-ui

1. Log in as a librarian
2. Go to a library detail view, different to My library
3. Go to Admin & Monitoring > My library
4. The URL is correct but not the information displayed 

**Expected behavior**
The content of the view should match the corresponding url.

**Software version**
https://github.com/rero/ng-core/commit/cb1af09e87ff031b2f9653aa9246986005295007
https://github.com/rero/rero-ils-ui/commit/2cd145c453ce1c3417971fb2a7e355af727079ac

**Comment by iGormilhit** [comment]
@AoNoOokami Is it still relevant? Or should it be in the rero-ils issues instead?

**Comment by AoNoOokami** [comment]
As the issue is no more present in v0.14.1 I close it.
