### ISSUE TITLE
Guessing current locale

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/ng-core#4]
The library have to guess the current locale by checking on : 

* browser languages
* html tag

**Comment by iGormilhit** [comment]
@sebastiendeleze I've removed it from the Issues management project, as I think this is a SONAR user story. Am I correct?

**Comment by sebastiendeleze** [comment]
I don't think it's relative to SONAR only, but at this time the language is guessed from lang property of html tag, which can be filled by the host project (SONAR or RERO-ILS). So in my opinion issue can be closed.

**Comment by iGormilhit** [comment]
So I'm closing it.
