### ISSUE TITLE
Multiple languages support

### ISSUE THREAD

**Issue by iGormilhit** [rero/ng-core#58]
**Describe the issue**
The project needs a way to support more i18n languages, and to configure which ones a specific instance will need.

**Expected behavior**
This should help projects like `rero-ils-ui` or `sonar-ui` to support more languages.

**Additional context**
When resolving this issue, the translated files in `rero-ils-ui` for Spanish, Arabic and Dutch, should be produced and synchronized to transifex, in order to recycle the existing translations in `rero_ils/ui` or on transifex.

**Comment by iGormilhit** [comment]
@sebastiendeleze @jma Is it still relevant?

**Comment by sebastiendeleze** [comment]
We can already configure languages independently for each projects, so for me this issue can be closed.

**Comment by iGormilhit** [comment]
I'm closing it.
